# Generated by Django 5.0.6 on 2024-06-22 03:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 날짜')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='상품명')),
                ('price', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000000)], verbose_name='상품가')),
                ('is_discount', models.BooleanField(default=False, verbose_name='할인중')),
                ('discount_price', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000000)], verbose_name='할인가')),
                ('detail', models.CharField(help_text='상품 디테일: 소재 등', max_length=256, verbose_name='디테일')),
                ('description', models.TextField(blank=True, null=True, verbose_name='상품설명')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='대문자로 자동 저장', max_length=10, verbose_name='사이즈')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '사이즈',
                'verbose_name_plural': '사이즈',
                'db_table': 'product_sizes',
            },
        ),
    ]
