# Generated by Django 5.0.6 on 2024-06-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='영문 혹은 한글로 전부 통일할것', max_length=32, verbose_name='컬러')),
                ('product', models.ManyToManyField(related_name='products', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '컬러',
                'verbose_name_plural': '컬러',
                'db_table': 'product_colors',
            },
        ),
    ]
