# Generated by Django 5.0.6 on 2024-06-22 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg?20200913095930', verbose_name='썸네일'),
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, null=True, verbose_name='사진')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '사진',
                'verbose_name_plural': '사진',
                'db_table': 'product_photos',
            },
        ),
    ]
